### ISSUE TITLE
New comments from reviewers 

### ISSUE THREAD

**Issue by ypriverol** [OmicsDI/ddipy#27]
- [x] After reviewing the codebase of https://github.com/OmicsDI/ddi-web-service/ it appears that there are almost no tests, but more importantly I did not found any trace of continuous integration. I can only recommend to enrich the tests, and enable it as you did for the clients, even though it might be harder due to the dependencies.

- [x] https://www.omicsdi.org/ws/dataset/pridr/PXD000210/ is now indicating that the database is missing but still uses a 500 while it should be a 404

- [x] In the python example of the client, providing a boolean argument while never indicating what it is add little to no information. Please either use named attribute, or remove it:

```python
res=client.get_dataset_details(domain="pride", accession="PXD000210")
# or
res=client.get_dataset_details(domain="pride", accession="PXD000210", debug=True)
```

- [x] https://www.omicsdi.org/ws/database/blabla/picture fails with a 500 error and a NullPointerException, it should indicate that `blabla` database does not exists, and return a status_code of 404
 
- [x] In dataset_client.py search method refuse to not specify `sortfield` or `order` while API allows it. Client should not introduce such restriction without a reason. Here after a snippet where arguments are optional (but still must not be an empty string).

```python
class DatasetClient:

    # (...)

    @staticmethod
    def search(query, sortfield=None, order=None, start=0, size=20, face_count=20):
        params = {
            "start": start,
            "size": size,
            "faceCount": face_count
        }
        if not query:
            raise BadRequest("missing parameter query", MISSING_PARAMETER, payload=None)
        else:
            params.update(query=query)
        if sortfield:
            params.update(sortfield=sortfield)
        if order:
            params.update(order=order)
```

**Comment by mindcrusher11** [comment]
updated changes and deployed to production as well
